exclude:
    - node_modules

sass:
    style: :compressed

plugins:
    - jekyll-remote-theme

github:
    private: true

site:
    title: TypeScript Libraries
    description: Libraries for TypeScript

theme: jekyll-theme-cayman
