title: TypeScriptLibs
description: Libraries for TypeScript
author: © TypeScriptLibs
email: bug@typescriptlibs.org
github_username:  typescriptlibs
rss: rss

feed_meta:
|
  <link type="application/atom+xml" rel="alternate" href="https://typescriptlibs.org/feed.xml" title="TypeScriptLibs">
	<link rel="apple-touch-icon" href="assets/appicon.png" />
	<link rel="mask-icon" href="assets/pinicon.svg" color="#609" />

github:
  private: true

header_pages:
  - support/index.md
  - index.md

show_excerpts: false

theme: minima

minima:
  date_format: "%Y-%m-%d"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
