exclude:
  - node_modules

sass:
  style: :compressed

remote_theme: typescriptlibs/typescriptlibs.github.theme

github:
  private: true

title: TypeScriptLibs.org
description: Libraries for TypeScript