title: TypeScriptLibs
description: Libraries for TypeScript
author: © TypeScriptLibs
email: bug@typescriptlibs.org
github_username:  typescriptlibs
rss: rss

show_excerpts: false

github:
    private: true

header_pages:
 - index.md
 - license.md

plugins:
 - jekyll-feed
 - jekyll-seo-tag

theme: minima

minima:
  date_format: "%Y-%m-%d"
