title: TypeScript Libraries
description: Libraries for TypeScript

github:
    private: true

plugins:
  - jekyll-remote-theme

remote_theme: typescriptlibs/minimtest

sass:
    style: :compressed

exclude:
    - node_modules
    - script
