exclude:
    - node_modules

sass:
    style: :compressed

plugins:
    - jekyll-remote-theme

remote_theme: typescriptlibs/typescriptlibs.github.theme

github:
    private: true

site:
    title: TypeScript Libraries
    description: Libraries for TypeScript
