url: https://typescriptlibs.org
title: TypeScriptLibs
description: Libraries for TypeScript
author: © TypeScriptLibs

email: bug@typescriptlibs.org
github_username:  typescriptlibs
rss: rss

github:
  private: true

header_pages:
  - support/index.md
  - index.md

show_excerpts: false

theme: minima

minima:
  date_format: "%Y-%m-%d"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
